site_name: DietPi.com-Dokumentation
site_url:  https://dietpi.de/docs/
site_description: Offizielle Dokumentationsseiten für DietPi OS
site_author: DietPi.com-Team
copyright: Copyright © 2022 DietPi.com | Dokumentation Verteilt unter <a target="_blank"
href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>

repo_name: DietPi-Docs
repo_url: https://github.com/DWHR-Pi/DietPi-Docs
edit_uri: edit/dev/docs/
docs_dir: docs

theme:
  name: Stoff
  custom_dir: overrides # https://www.mkdocs.org/user-guide/styling-your-docs/#using-the-theme-custom_dir

  # JavaScript von MkDocs nicht einschließen
  include_search_page: false
  search_index_only: true

  language: en
  features:
  - navigation.tabs
  #logo: assets/images/logo.png
  favicon: https://dietpi.com/favicon.ico

markdown_extensions:
- markdown.extensions.admonition # Hervorgehobene Warn-/Infoblöcke
- markdown.extensions.attr_list # Benutzerdefinierte HTML-Attribute festlegen {: }
- markdown.extensions.codehilite: # Syntax in Codeblöcken hervorheben
    guess_lang: false # # Sprache muss immer für Syntax-Highlighting definiert werden
- markdown.extensions.footnotes # Fußnoten [^1]
- markdown.extensions.meta # Metadaten (Seitentitel und Beschreibung) oben im Markdown-Dokument definieren
- markdown.extensions.smarty # Bindestriche, Unterstriche, drei Punkte und Anführungszeichen automatisch in Textsymbole umwandeln
- markdown.extensions.tables # Tabellen
- markdown.extensions.toc: # HTML-ID-Attribut zu Headern hinzufügen
    permalink: true # Header sind Links zu sich selbst
- pymdownx.betterem: # Intuitivere Hervorhebungsbehandlung
    smart_enable: all # Noch intelligenter für beide (Stern und Unterstrich) Syntax => GitHub-like
- pymdownx.details # Reduzierbare Detailblöcke
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.keys # Tastensymbole der Tastatur
- pymdownx.magiclink: # Verlinkt automatisch URLs und E-Mail-Adressen, die keine spitzen Klammern sind, und ermöglicht das Kürzen und Visualisieren von Git-Repo-Links
    repo_url_shortener: true
    repo_url_shorthand: true
- pymdownx.superfences # Eingegrenzte Codeblöcke, zB innerhalb von Listen, Ermahnungen, Details oder Tabbed-Blöcken
- pymdownx.tabbed # Inhaltsblöcke mit Registerkarten

# Markdown-Erweiterungen, die in Zukunft verwendet werden könnten
#
#- markdown.extensions.abbr # Abkürzungen <abbr>
#- markdown.extensions.def_list # Definitionslisten
#- markdown.markdown-de.md_in_html # Markdown-Syntax innerhalb von HTML-Tags zulassen
#- pymdownx.arithmatex # Unterstützung mathematischer Begriffe in LaTeX
#- pymdownx.caret # Hochstellen von <sup> und Einfügen von <ins> über Caret ^
#- pymdownx.critic # Text kommentieren, hervorheben, hinzufügen oder durchstreichen
#- pymdownx.highlight # Konfigurieren Sie die Codehervorhebung für alle Codedefinitionen, eingezäunt, inline und durch Einrückung blockiert
#- pymdownx.inlinehilite # Syntax im Inline-Code hervorheben
#- pymdownx.mark # Text markieren <mark> via ==text==
#- pymdownx.smartsymbols # Einfache Symbolsyntax (Warenzeichen, Copyright, Pfeile, ...)
#- pymdownx.snippets # Fügen Sie Markdown-Dateien in andere ein
#- pymdownx.tilde # Tiefgestellter <sub> und durchgestrichener <del> Text über Tilde ~

plugins:
- search
- minify:
    minify_html: true
    htmlmin_opts:
      # https://htmlmin.readthedocs.io/en/latest/reference.html#main-functions
      remove_comments: true
      remove_all_empty_space: true
      reduce_boolean_attributes: true
      remove_optional_attribute_quotes: true
      convert_charrefs: true
    minify_css: true
    css_files:
    - assets/stylesheets/custom.css
    #minify_js: true
    #js_files:
    #- assets/javascripts/custom.js

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/MichaIng/DietPi
  - icon: fontawesome/solid/home
    link: https://dietpi.com/
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/DietPi_

extra_css:
- assets/stylesheets/custom.css

nav:
- Heim:
  - Übersicht: index-de.md
  - Installation: install-de.md
  - Erste Schritte: getting_started-de.md
  - Softwareoptionen: software-de.md
  - DietPi-Tools: dietpi_tools-de.md
  - Anwendungshinweise / HowTo: usage-de.md
  - Unterstützte Hardware: hardware-de.md
  - Veröffentlichungen: releases-de.md
  - Referenzen: Referenzen-de.md
- OPTIMIERTE SOFTWARE:
  - Übersicht: software-de.md
  - Erweiterte Vernetzung: software/advanced_networking-de.md
  - BitTorrent & Download-Tools: software/bittorrent-de.md
  - Kamera & Überwachung: software/camera-de.md
  - Cloud- & Backup-Systeme: software/cloud-de.md
  - Datenbanken & Datenspeicher: software/databases-de.md
  - Desktops & Dienstprogramme: software/desktop-de.md
  - Entwicklung & Programmierung: software/programming-de.md
  - Verteilte Projekte: software/distributed_projects-de.md
  - DNS-Server: software/dns_servers-de.md
  - Dateiserver: software/file_servers-de.md
  - Gaming & Emulation: software/gaming-de.md
  - Hardware-Projekte: software/hardware_projects-de.md
  - Hausautomation: software/home_automation-de.md
  - Logging-Systeme: software/log_system-de.md
  - Mediensysteme: software/media-de.md
  - Druckserver: software/printing-de.md
  - Remotedesktop & Fernzugriff: software/remote_desktop-de.md
  - Social & Suche: software/social-de.md
  - SSH-Server: software/ssh-de.md
  - Systemsicherheit: software/system_security-de.md
  - Systemstatistik & Management: software/system_stats-de.md
  - VPN: software/vpn-de.md
  - Webentwicklung: software/webserver_stack-de.md
- VERÖFFENTLICHUNGEN:
  - Übersicht: releases-de.md
  - v8.1 Februar 2022: releases/v8_1-de.md
  - v8.0 Januar 2022: releases/v8_0-de.md
  - v7.9 Dezember 2021: releases/v7_9-de.md
  - v7.8 November 2021: releases/v7_8-de.md
  - v7.7 Oktober 2021: releases/v7_7-de.md
  - v7.6 September 2021: releases/v7_6-de.md
  - v7.5 August 2021: releases/v7_5-de.md
  - v7.4 Juli 2021: releases/v7_4-de.md
  - v7.3 Juni 2021: releases/v7_3-de.md
  - v7.2 Mai 2021: releases/v7_2-de.md
  - v7.1 April 2021: releases/v7_1-de.md
  - v7.0 Februar 2021: releases/v7_0-de.md
  - v6.34 Dezember 2020: releases/v6_34-de.md
  - v6.33 Oktober 2020: releases/v6_33-de.md
  - v6.32 August 2020: releases/v6_32-de.md
  - v6.31 Juli 2020: releases/v6_31-de.md
  - v6.30 Mai 2020: releases/v6_30-de.md
  - v6.29 Mai 2020: releases/v6_29-de.md
  - v6.28 Januar 2020: releases/v6_28-de.md
  - v6.27 Januar 2020: releases/v6_27-de.md
  - Früher: https://dietpi.com/phpbb/viewforum.php?f=10
- GEMEINSCHAFT:
  # Die erste Datei "socialmedia-de.md" wird hinzugefügt, ansonsten springt in manchen Browsern ein Klick auf "Community" direkt zum ersten Eintrag
  # Das war der Fall, dass ein Klick direkt auf die Github-Seite gesprungen ist. (Dann verlassen Sie unsere geniale Seite dietpi.com/docs...) :-)
  - Soziale Medien: socialmedia-de.md
  - DietPi-GitHub-Seite: https://github.com/MichaIng/DietPi
  - DietPi-Blogseite: https://dietpi.com/blog/
  - Probleme melden: https://github.com/MichaIng/DietPi/issues
  - Features anfordern: https://github.com/MichaIng/DietPi/issues/new/choose
  - DietPi-Forum: https://dietpi.com/phpbb/
  - Community-Tutorials: https://dietpi.com/phpbb/viewforum.php?f=15
  - Fehlerbehebung: https://dietpi.com/phpbb/viewforum.php?f=11
